apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      serviceAccountName: kafka-sa  # ✅ IAM 인증 역할 연동을 위한 서비스 계정
      containers:
        - name: spring-app
          image: 639965457439.dkr.ecr.ap-northeast-2.amazonaws.com/spring-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: KAFKA_SERVER
              value: "b-1.podopickermsk.26k7qa.c3.kafka.ap-northeast-2.amazonaws.com:9098,b-2.podopickermsk.26k7qa.c3.kafka.ap-northeast-2.amazonaws.com:9098"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: REDIS_HOST
              value: redis-cluster.backend.svc.cluster.local
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: recaptcha-secret
                  key: secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: google-client-secret
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: kakao-client-id
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: kakao-client-secret
            - name: NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: naver-client-id
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: naver-client-secret
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: kakao-redirect-uri
            - name: NAVER_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: naver-redirect-uri
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: host
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: MAIL_NAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: name
            - name: COOLSMS_KEY
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: key
            - name: COOLSMS_SECRET
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: secret
            - name: PETHARMONY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: petharmony-phone
            - name: IAMPORT-API-KEY
              valueFrom:
                secretKeyRef:
                  name: iamport-secret
                  key: api-key
            - name: IAMPORT-API-SECRET
              valueFrom:
                secretKeyRef:
                  name: iamport-secret
                  key: api-secret
